version: '3.8'

networks:
    app-network:
        driver: bridge

services:
    db:
        container_name: postgres-db
        image: postgres:16-alpine
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '${DB_PORT}:5432'
        volumes: 
            - '../database/postgres-data:/var/lib/postgresql/data'
        networks:
            - app-network

    api:
        build: .
        container_name: backend-api
        restart: always
        ports:
            - '${SERVER_PORT}:8080'
            - '${DT_SOCKET_PORT}:8000'
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - app-network
