export const path = {
  home: '/',
  auth: '/auth',
  login: '/auth/login',
  register: '/auth/register',
  patients: '/patients',
  patientDetail: '/patients/:patientId',
  patientDetailExamination: '/patients/:patientId/medical-records/:examinationId',
  personals: '/personals',
  game: '/game',
  gamev2: '/game/v2',
  pvp: '/game/:gameId',
  pvpv2: '/game/v2/:gameId',
  botv2: '/game/v2/bot/:gameId',
  quickMatch: '/game/quickmatch',
  playWithBot: '/game/v2/play-with-bot',
  chat: '/chat',
  chatbox: '/chat/:id',
  friend: '/friend'
} as const
