name: Build and Deploy
on:
  workflow_dispatch: {}
  push:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy .env
        run: cp .env.example .env
      - name: Restart server
        run: docker-compose up -d --build
