name: Reset database
on:
  workflow_dispatch: {}
  push:
    paths:
      - "database/**"
    branches:
      - main

jobs:
  reset-db:
    runs-on: self-hosted
    if: github.event.repository.owner.login == 'LongTCH'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy .env
        run: cp ~/.env .env
      - name: Install dependencies
        run: cd database && npm install -g yarn && npm i
      - name: Stop server
        run: docker compose down api
      - name: Reset database
        run: cd database && npm run db:reset
      - name: Start server
        run: docker compose up -d api
