name: Reset database
on:
  workflow_dispatch: {}
  push:
    paths:
      - "database/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event.repository.owner.login == 'LongTCH'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy .env
        run: cp .env.example .env
      - name: Install dependencies
        run: cd database && npm i
      - name: Reset database
        run: cd database && npm run db:reset
